### ISSUE TITLE
Foutieve weergave van highscores bij gebruik van /leaderboard type all-time

### ISSUE THREAD

**Issue by Slober3** [grYs51/Astolfo#426]
**Beschrijving:**
Bij het raadplegen van de highscores met behulp van het commando /leaderboard type all-time is mij opgevallen dat de ranglijsten niet consistent zijn. Sommige gebruikers zijn onverwacht gedaald in de ranking, terwijl dit niet overeenkomt met eerdere weergaven van dezelfde lijst.

**Stappen om te reproduceren:**

- Gebruik het commando /leaderboard type all-time in de bot.
- Vergelijk de resultaten met een eerdere weergave van dezelfde lijst.
- Merk op dat er verschillen zijn in de rangschikking van gebruikers.

**Verwacht gedrag:**
De highscores zouden consistent moeten blijven over tijd, tenzij er een expliciete reden is voor een wijziging (bijvoorbeeld nieuwe scores).

**Extra informatie:**
Mogelijk is er een fout in de opslag of verwerking van de highscores.
Als er onlangs een update is geweest, kan dit invloed hebben gehad op de data.
Kunnen jullie dit onderzoeken en indien nodig corrigeren? 😊

Labels: 
Bug Leaderboard 
Priority: Medium

**Comment by grYs51** [comment]
Hi Slober3,

Thank you for reporting this issue with the /leaderboard type all-time rankings. I appreciate the detailed steps you provided to reproduce the problem; this will help us investigate more effectively.

Based on your description, it seems there may be an inconsistency in how scores are processed or displayed. Here’s what we’ll do to address this:

Investigate the Source: We’ll review the logic behind how all-time highscores are calculated, stored, and retrieved to identify any discrepancies.
Check Recent Updates: If any updates were recently deployed, we’ll verify if they introduced changes that might have impacted the leaderboard.
Run Tests: We’ll replicate your steps internally to confirm the issue and ensure we have consistent results across different scenarios.
Implement Fixes (if needed): Should we find a bug, we’ll apply the necessary fixes and ensure the leaderboard reflects accurate and stable rankings.
Your report has been logged under the Bug Leaderboard category with a Medium priority for resolution. I’ll follow up with updates as soon as we’ve identified the root cause and implemented any necessary changes.

Thank you for your patience and for helping us improve! 😊 If you notice any additional details or patterns, feel free to share them with us.

Best regards,
Gra
